export const localTexts = {
  customerList: "لیست مشتریان",
  customerEmptyState:"متاسفانه هنوز اطلاعات مشتریان خود را ثبت نکرده اید. در این قسمت شما لیست مشتریان شامل تاریخ عضویت، تعداد سفارش، مجموع پرداختی‌ها، برچسب‌ها و وضعیت مشتری را مشاهده خواهید کرد. ",
  addCustomer:"افزودن مشتری",
  handyAdd:"افزودن دستی",
  addWithCSV:"افزودن با فایل CSV",
  nameAndLastName:"نام و نام خانوادگی",
  fillNameAndLastName:"نام و نام خانوادگی مشتری را وارد کنید.",
  phone:"شماره همراه",
  addPhoneNumber:"شماره همراه مشتری را وارد کنید",
  address:"آدرس",
  addAddress:"آدرس را وارد کنید",
  close:"بستن",
  submit:"افزودن",
  customer:"مشتری",
  customerSubsDate:"تاریخ عضویت",
  averagePayment:"میانگین پرداختی",
  OrderNumber:"تعداد سفارش",
  customerValue:"ارزش مشتری",
  customerTag:"برچسب مشتری",
  status:'وضعیت',
  action:"عملیات",
  categoryEmptyState:'دسته‌بندی‌‌ای برای مشتریان تعریف نکرده‌اید.',
  addCategory:'افزودن دسته‌بندی',
  categoryName:'عنوان دسته‌بندی',
  numberOfCustomer:'تعداد مشتریان',
  statusOfCategory:'وضعیت دسته‌بندی',
  goalCutsomer:'مشتریان هدف',
  amountOfCredit:'میزان اعتبار',
  rangOfUsingCredit:'بازه مصرف اعتبار',
  DiscountName:'عنوان تخفیف',
  discountSetting:'تنظیمات تخفیف',
  amountOfDiscount:'مقدار تخفیف',
  targetCustomer:'مشتریان هدف',
  discountStatus:'وضعیت تخفیف',
  rangOfDiscount:'زمان شروع و پایان',
  copounName:'عنوان کوپن',
  copounType:'نوع کوپن',
  gift:'پاداش',
  statusOfCopoun:'وضعیت کوپن'
};
